### ISSUE TITLE
Cannot be loaded on Linux server

### ISSUE THREAD

**Issue by liplum** [sk7725/BetaMindy#135]
**Platform**: *Linux Ubuntu*

**Build**: *135*

**Mod Version**: *Build v1.073*

**Issue**: *Server cannot load this mod.*

**Steps to reproduce**: *Put the "file BetaMindy.jar" into folder "./config/mods". Then run the game by using java -jar*

**Server console output**:
`[01-26-2022 18:09:14] [E] Failed to load mod file config/mods/BetaMindy.jar. Skipping.
[01-26-2022 18:09:14] [E] java.lang.UnsatisfiedLinkError: 'long arc.audio.Soloud.filterBiquad()'
	at arc.audio.Soloud.filterBiquad(Native Method)
	at arc.audio.Filters$BiquadFilter.<init>(Filters.java:11)
	at betamindy.util.MFilters$1.<init>(MFilters.java:20)
	at betamindy.util.MFilters.<init>(MFilters.java:19)
	at betamindy.BetaMindy.<clinit>(BetaMindy.java:51)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:466)
	at mindustry.mod.Mods.loadMod(Mods.java:799)
	at mindustry.mod.Mods.loadMod(Mods.java:714)
	at mindustry.mod.Mods.load(Mods.java:363)
	at mindustry.Vars.init(Vars.java:320)
	at mindustry.server.ServerLauncher.init(ServerLauncher.java:47)
	at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:65)
	at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:53)
[01-26-2022 18:09:15] [I] Server loaded. Type 'help' for help.`
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- [X] **I have updated to the latest release (https://github.com/sk7725/BetaMindy/releases) to make sure my issue has not been fixed.**

---

**Comment by sk7725** [comment]
Fixed in latest action, I'll release it tomorrow.

**Comment by sk7725** [comment]
> Thanks. And I'm new in Mindustry modding. Could you tell me why this is the problem? By a glance, I guess the reason is that the Block "Note Player" requires something about audio but audio system is "Client Side Only" and can't be found on the server.

It was the sound filter block, sound filters are client side only.
now fixed in the latest release.
