### ISSUE TITLE
Master Key Turret Crashes

### ISSUE THREAD

**Issue by Hot-Sausage07** [sk7725/BetaMindy#151]
[crash-report-06_22_2022_16_46_25.txt](https://github.com/sk7725/BetaMindy/files/8956100/crash-report-06_22_2022_16_46_25.txt)
Selecting turret using master key crashes when i select a vanilla erekir turret
Well i select here is titan

**Comment by Hot-Sausage07** [comment]
```
Mindustry has crashed. How unfortunate.
Version: bleeding-edge build 22697
OS: Windows 10 x64 (amd64)
Java Version: 1.8.0_72
Runtime Available Memory: 891mb
Cores: 2
Mods: betamindy:1.09
[#b59e72]Demo of Chaos Itself[], prog-mats:26, time-control:0.2, unity:0.1-youngcha.2.8

java.lang.NullPointerException
	at betamindy.world.blocks.defense.turrets.HijackTurret$HijackTurretBuild.powerUsage(HijackTurret.java:226)
	at mindustry.world.consumers.ConsumePowerDynamic.requestedPower(ConsumePowerDynamic.java:18)
	at mindustry.world.blocks.power.PowerGraph.getPowerNeeded(PowerGraph.java:104)
	at mindustry.world.blocks.power.PowerGraph.update(PowerGraph.java:219)
	at mindustry.gen.PowerGraphUpdater.update(PowerGraphUpdater.java:165)
	at mindustry.entities.EntityGroup.update(EntityGroup.java:76)
	at mindustry.gen.Groups.update(Groups.java:79)
	at mindustry.core.Logic.update(Logic.java:541)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:168)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:201)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:189)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

```
