### ISSUE TITLE
any of the hacking turrets keep making this crash

### ISSUE THREAD

**Issue by hjhjimoy1** [sk7725/BetaMindy#152]
Mindustry has crashed. How unfortunate.
Version: bleeding-edge build 22690
OS: Windows 10 x64 (amd64)
Java Version: 16.0.1
Runtime Available Memory: 4062mb
Cores: 8
Mods: betamindy:1.09
[#b59e72]Demo of Chaos Itself[], dev-mode:3.3.2, informatis:1.6, time-control:0.2, ui-lib:3.16.6, unit-factory:3.5.0, betamindy-music:1.0, green-mod:0.1, hackustry:4, invincible-cheat-mod-v6:2.8.4, team-changer:1.0

java.lang.NullPointerException: Cannot read field "buffered" because "cons" is null
	at informatis.core.BarInfo.getInfo(BarInfo.java:67)
	at informatis.core.Main.lambda$init$1(Main.java:29)
	at arc.Events.lambda$run$2(Events.java:20)
	at arc.Events.fire(Events.java:36)
	at mindustry.core.Logic.update(Logic.java:475)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:168)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:201)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:189)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

**Comment by MrRoomba** [comment]
I have the same issue with the unit pipes and ducts

**Comment by SMOLKEYS** [comment]
> at informatis.core.BarInfo.getInfo(BarInfo.java:67)
> at informatis.core.Main.lambda$init$1(Main.java:29)

This is informatis, not betamindy.

**Comment by Sharlottes** [comment]
can you just update to latest action build?
