### ISSUE TITLE
when i tried to shoot any of the hijacking turrets this happens

### ISSUE THREAD

**Issue by hjhjimoy1** [sk7725/BetaMindy#155]
industry has crashed. How unfortunate.
Version: bleeding-edge build 22810
OS: Windows 10 x64 (amd64)
Java Version: 16.0.1
Runtime Available Memory: 4062mb
Cores: 8
Mods: betamindy:1.09
[#b59e72]Demo of Chaos Itself[], dev-mode:3.3.2, erekir-expansion:0.60 Pre-Alpha, multi-crafter:1, test-utils:41, time-control:0.2, ui-lib:3.16.6, unit-factory:3.5.0, betamindy-music:1.0, green-mod:0.1, hackustry:4, invincible-cheat-mod-v6:2.8.4, team-changer:1.0, unitinfo6:1.4.3, v5dustry:0.1

java.lang.IllegalStateException: Array is empty.
	at arc.struct.Seq.peek(Seq.java:728)
	at mindustry.world.blocks.defense.turrets.Turret$TurretBuild.useAmmo(Turret.java:469)
	at mindustry.world.blocks.defense.turrets.Turret$TurretBuild.shoot(Turret.java:538)
	at mindustry.world.blocks.defense.turrets.Turret$TurretBuild.updateShooting(Turret.java:511)
	at mindustry.world.blocks.defense.turrets.Turret$TurretBuild.updateTile(Turret.java:409)
	at betamindy.world.blocks.defense.turrets.HijackTurret$HijackTurretBuild.updateTile(HijackTurret.java:151)
	at mindustry.gen.Building.update(Building.java:2072)
	at mindustry.entities.EntityGroup.update(EntityGroup.java:76)
	at mindustry.gen.Groups.update(Groups.java:79)
	at mindustry.core.Logic.update(Logic.java:541)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:229)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:201)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:189)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

**Comment by littlekatter330** [comment]
this happens to me too

**Comment by ManuWar73** [comment]
SK KNOWS THIS.

**Comment by ManuWar73** [comment]
Why i know he/she knows that? Well, he/she put that on the patch notes of the latest update. Please read latest releases'  notes

**Comment by Evanevoyo** [comment]
I found this out the hard way on a really developed save, enemy came, auto saved less than a sec before it came in range and turret shoots and crashes. I cant even paused in time cuz its instantly in range and just crashes
