### ISSUE TITLE
Live list of bugs and crashes

### ISSUE THREAD

**Issue by SMOLKEYS** [sk7725/BetaMindy#179]
**Platform**: Android

**Build**: 145.1

**Mod Version**: v1.11

**Crashes**:

Crash 1:
1. Place a trading post
2. Click it
3.
```
java.lang.LinkageError: Method float betamindy.world.blocks.storage.TradingPost$TradingPostBuild.angleTo(float, float) overrides final method in class Lmindustry/gen/Building; (declaration of 'betamindy.world.blocks.storage.TradingPost$TradingPostBuild' appears in /storage/emulated/0/Android/data/io.anuke.mindustry/files/mods/sk7725betamindy.zip)
	at dalvik.system.DexFile.defineClassNative(Native Method)
	at dalvik.system.DexFile.defineClass(DexFile.java:298)
	at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:291)
	at dalvik.system.DexPathList$Element.findClass(DexPathList.java:772)
	at dalvik.system.DexPathList.findClass(DexPathList.java:532)
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:245)
	at mindustry.android.AndroidLauncher$1$1.loadClass(AndroidLauncher.java:2)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at betamindy.content.MindyBlocks.load(MindyBlocks.java:2094)
	at betamindy.BetaMindy.loadContent(BetaMindy.java:170)
	at mindustry.mod.Mods.loadContent(Mods.java:4)
	at mindustry.core.ContentLoader.createModContent(ContentLoader.java:2)
	at mindustry.ClientLauncher.lambda$setup$4(ClientLauncher.java:2)
	at mindustry.ClientLauncher.$r8$lambda$iJ-6sZ_ACwQARuCa-MLy6VoTzXg(Unknown Source:0)
	at mindustry.ClientLauncher$$ExternalSyntheticLambda2.run(Unknown Source:22)
	at arc.assets.AssetManager$1.loadSync(AssetManager.java:1)
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:9)
	at arc.assets.AssetLoadingTask.update(AssetLoadingTask.java:4)
	at arc.assets.AssetManager.updateTask(AssetManager.java:2)
	at arc.assets.AssetManager.update(AssetManager.java:5)
	at arc.assets.AssetManager.update(AssetManager.java:9)
	at mindustry.ClientLauncher.update(ClientLauncher.java:4)
	at arc.backend.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:22)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1573)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)
```

Crash 2:
1. Place an anusafe
2. Click it
3.
```
java.lang.LinkageError: Method float betamindy.world.blocks.storage.AnucoinVault$AnucoinVaultBuild.angleTo(float, float) overrides final method in class Lmindustry/gen/Building; (declaration of 'betamindy.world.blocks.storage.AnucoinVault$AnucoinVaultBuild' appears in /storage/emulated/0/Android/data/io.anuke.mindustry/files/mods/sk7725betamindy.zip)
	at dalvik.system.DexFile.defineClassNative(Native Method)
	at dalvik.system.DexFile.defineClass(DexFile.java:298)
	at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:291)
	at dalvik.system.DexPathList$Element.findClass(DexPathList.java:772)
	at dalvik.system.DexPathList.findClass(DexPathList.java:532)
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:245)
	at mindustry.android.AndroidLauncher$1$1.loadClass(AndroidLauncher.java:2)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at betamindy.content.MindyBlocks.load(MindyBlocks.java:2054)
	at betamindy.BetaMindy.loadContent(BetaMindy.java:170)
	at mindustry.mod.Mods.loadContent(Mods.java:4)
	at mindustry.core.ContentLoader.createModContent(ContentLoader.java:2)
	at mindustry.ClientLauncher.lambda$setup$4(ClientLauncher.java:2)
	at mindustry.ClientLauncher.$r8$lambda$iJ-6sZ_ACwQARuCa-MLy6VoTzXg(Unknown Source:0)
	at mindustry.ClientLauncher$$ExternalSyntheticLambda2.run(Unknown Source:22)
	at arc.assets.AssetManager$1.loadSync(AssetManager.java:1)
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:9)
	at arc.assets.AssetLoadingTask.update(AssetLoadingTask.java:4)
	at arc.assets.AssetManager.updateTask(AssetManager.java:2)
	at arc.assets.AssetManager.update(AssetManager.java:5)
	at arc.assets.AssetManager.update(AssetManager.java:9)
	at mindustry.ClientLauncher.update(ClientLauncher.java:4)
	at arc.backend.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:22)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1573)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)
```

**Bugs**: 

Item, Unit, and Extra Shops don't work.

Anucoin Source doesn't work.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- [X] **I have updated to the latest release (https://github.com/sk7725/BetaMindy/releases) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725.

Actively updating.

**Comment by SMOLKEYS** [comment]
every crash so far is a LinkageError

![Screenshot_20230710-210620_AppErrorsTracking](https://github.com/sk7725/BetaMindy/assets/75618732/21e14d4c-f85e-4107-b0af-b1852668c03a)
