### ISSUE TITLE
Phisher Crash

### ISSUE THREAD

**Issue by AidenMishael** [sk7725/BetaMindy#186]
**Platform**: *Android//Windows/Linux*
Windows
**Build**: *The build number under the title in the main menu. Required.*
24539
**Mod Version**: *(optional)*

**Issue**: *Explain your issue in detail.*
When I use the Phisher, it always crash. And it always says something about array is missing
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
By using the Phisher.
**Save file**: *The (zipped) save file you were playing on when the bug happened. Not required, but you will be asked for it in certain bugs.*

**Last log**: *The `last_log.txt` from your game folder (.../Mindustry). REQUIRED if a certain block is not working at ALL, usually the case in headless servers.*

**Crash logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
aimclient:1.0.0, auto-translate:1, betamindy:1.09, byte-logic-mod:v1.0.1, canvases:1.0, classicv5:1.072 Beta, compress-this!:1.7.6, cyber-io:5.0, dev-mode:3.3.2, df:1.0.0, drift:lol, ei:1.5 [B3], erekir-logic:Release V1, exogenesis:[blue]1.9.1, factroundustry:1, golden-silicon:1.2.1, heatgaming:null, invincible-cheat-mod-v7:3.1.0, liquidsplus:1.2 Alpha, lp:4.00, math-stuff:1.1, me:2.0 - The Erekir Update(1), mindustrinity:0.7.2, miner-tools:1.7.4.2, minimod:1, multi-crafter:1.0, mythril-uraic:0.1, opmod:1.6.4, prog-mats:26.6, projectv5-mod:0.1.0 Beta, roombas:0.3, schematics-pack:9, serilia:1.2, shar:0.2v, test:1.0, test-utils:48, time-control:0.2, toolkit:1, trade-it:3.0, uaw:v0.8.3, unit-factory:3.5.0, yawym:0.1, auto-updater:0.9, beautiful-bullet:1, better-menders:1, exotic-mod:0.7 Alpha, free-campaign:0.2, mind-util:1.3.0, mindus:0.1.0.3, parkour-mod:2.4, super-cheat:0.91, turret-expansion:0.0.2 Beta, ui-lib:4.18.0

arc.util.ArcRuntimeException: arc.util.ArcRuntimeException: Couldn't load dependencies of asset: contentinit
	at arc.assets.AssetManager.handleTaskError(AssetManager.java:669)
	at arc.assets.AssetManager.update(AssetManager.java:441)
	at arc.assets.AssetManager.update(AssetManager.java:464)
	at mindustry.ClientLauncher.update(ClientLauncher.java:208)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
Caused by: arc.util.ArcRuntimeException: Couldn't load dependencies of asset: contentinit
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:104)
	at arc.assets.AssetLoadingTask.update(AssetLoadingTask.java:73)
	at arc.assets.AssetManager.updateTask(AssetManager.java:590)
	at arc.assets.AssetManager.update(AssetManager.java:439)
	... 6 more
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:102)
	... 9 more
Caused by: java.lang.NullPointerException
	at mindustry.world.blocks.defense.turrets.LaserTurret.setStats(LaserTurret.java:30)
	at mindustry.ctype.UnlockableContent.checkStats(UnlockableContent.java:78)
	at MinerTools.override.stats.MStats$StatOverride.override(MStats.java:22)
	at MinerTools.content.Contents.initBlocks(Contents.java:68)
	at MinerTools.content.Contents.init(Contents.java:22)
	at MinerTools.MinerTools.lambda$new$0(MinerTools.java:29)
	at arc.Events.fire(Events.java:53)
	at arc.Events.fire(Events.java:43)
	at mindustry.core.ContentLoader.init(ContentLoader.java:89)
	at mindustry.ClientLauncher.lambda$setup$7(ClientLauncher.java:177)
	at arc.assets.AssetManager$1.loadAsync(AssetManager.java:328)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:52)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:16)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- [X] **I have updated to the latest release (https://github.com/sk7725/BetaMindy/releases) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725.

**Comment by sk7725** [comment]
known bug as anuke updated the turret system

**Comment by AidenMishael** [comment]
m'k
