### ISSUE TITLE
hacker turrets crashes the game

### ISSUE THREAD

**Issue by terracatmeown** [sk7725/BetaMindy#193]
If i use any of hacker turrets it crashes the game

Mindustry has crashed. How unfortunate.
Version: release build 146
OS: Windows 10 x64 (amd64)
Java Version: 16.0.1
Runtime Available Memory: 8160mb
Cores: 12
Mods: betamindy:1.1
[#b59e72]Demo of Chaos Itself[]

java.lang.IllegalStateException: Array is empty.
	at arc.struct.Seq.peek(Seq.java:737)
	at mindustry.world.blocks.defense.turrets.Turret$TurretBuild.useAmmo(Turret.java:503)
	at mindustry.world.blocks.defense.turrets.Turret$TurretBuild.shoot(Turret.java:572)
	at mindustry.world.blocks.defense.turrets.Turret$TurretBuild.updateShooting(Turret.java:546)
	at mindustry.world.blocks.defense.turrets.Turret$TurretBuild.updateTile(Turret.java:438)
	at betamindy.world.blocks.defense.turrets.HijackTurret$HijackTurretBuild.updateTile(HijackTurret.java:150)
	at mindustry.gen.Building.update(Building.java:2199)
	at mindustry.entities.EntityGroup.update(EntityGroup.java:83)
	at mindustry.gen.Groups.update(Groups.java:83)
	at mindustry.core.Logic.update(Logic.java:483)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:237)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

**Comment by traincrisis** [comment]
the hacker turrets are the green turrets?

**Comment by Dcksp2468** [comment]
@traincrisis i also had this problem, any turret that related to the hacker turret, not just the green one.
