### ISSUE TITLE
Crashing the game with spinners and pistons

### ISSUE THREAD

**Issue by ThePythonGuy3** [sk7725/BetaMindy#64]
**Platform**: *Windows*

**Build**: *BE 21417*

**Mod Version**: *1.0*

**Issue**: *Spinning a piston crashes the game*

**Steps to reproduce**: *Place a spinner, place a piston in front of it, power the spinner.*

**Crash logs**: *Mindustry has crashed. How unfortunate.
Version: bleeding-edge build 21417
OS: Windows 10 x64
Java Version: 15.0.2
Java Architecture: 64
3 Mods: betamindy:1.0
[#b59e72]Demo of Chaos Itself[], dev-mode:2.3.2, ui-lib:2.16.6

java.lang.NoSuchMethodError: 'arc.graphics.g2d.TextureRegion mindustry.world.blocks.payloads.BuildPayload.icon(mindustry.ui.Cicon)'
	at betamindy.world.blocks.distribution.Spinner$SpinnerBuild.drawPay(Spinner.java:330)
	at betamindy.world.blocks.distribution.Spinner$SpinnerBuild.drawSpinning(Spinner.java:306)
	at betamindy.world.blocks.distribution.Spinner$SpinnerBuild.draw(Spinner.java:280)
	at mindustry.world.Block.drawBase(Block.java:269)
	at mindustry.graphics.BlockRenderer.drawBlocks(BlockRenderer.java:327)
	at mindustry.core.Renderer.draw(Renderer.java:266)
	at mindustry.core.Renderer.update(Renderer.java:119)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:174)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:165)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:153)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:45)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:38)
*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- [X] **I have updated to the latest release (https://github.com/sk7725/BetaMindy/releases) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725.

**Comment by sk7725** [comment]
BE crashes spinners, which is fixed. Wait for the next Mindustry BE or v129 or something.

**Comment by ThePythonGuy3** [comment]
awesome

**Comment by ThePythonGuy3** [comment]
but spinners dont crash the game, only with pistons

**Comment by sk7725** [comment]
> but spinners dont crash the game, only with pistons

(spinners spinning spin-tastic (spinning functional) blocks do not crash, but everything else does. try spinning a copper wall and it yields the same results)

**Comment by ThePythonGuy3** [comment]
interesting, k back to intellij

**Comment by sk7725** [comment]
update: fixed
