### ISSUE TITLE
Error when pressing up arrow key

### ISSUE THREAD

**Issue by rmperkow** [sk7725/BetaMindy#65]
**Platform**: *Android//Windows/Linux*
Windows
**Build**: *The build number under the title in the main menu. Required.*
126.2
**Mod Version**: *(optional)*
1.0
**Issue**: *Explain your issue in detail.*
Pressing the up arrow key causes a hardmode error.
![image](https://user-images.githubusercontent.com/63563342/125815322-e99c57f1-ed19-4be0-a593-f263483a162d.png)

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Press the up arrow key in a game.
**Save file**: *The (zipped) save file you were playing on when the bug happened. Not required, but you will be asked for it in certain bugs.*
Not required, can be reproduced in any game session
**Last log**: *The `last_log.txt` from your game folder (.../Mindustry). REQUIRED if a certain block is not working at ALL, usually the case in headless servers.*
You might need this
[I] [GL] Version: OpenGL 4.6.0 / Intel / Intel(R) HD Graphics 530
[I] [GL] Max texture size: 16384
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 1.8.0_72
[W] Shader shaders/mesh.vert | shaders/planet.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing

[W] Shader shaders/default.vert | shaders/blockbuild.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing

[W] Shader shaders/screenspace.vert | shaders/shield.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing

[W] Shader shaders/screenspace.vert | shaders/buildbeam.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing

[W] Shader shaders/default.vert | shaders/unitbuild.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing

[W] Shader shaders/default.vert | shaders/darkness.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing

[W] Shader shaders/screenspace.vert | shaders/light.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing

[W] Shader shaders/screenspace.vert | shaders/water.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing

[W] Shader shaders/screenspace.vert | shaders/mud.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing

[W] Shader shaders/screenspace.vert | shaders/tar.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing

[W] Shader shaders/screenspace.vert | shaders/slag.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing

[W] Shader shaders/screenspace.vert | shaders/space.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing

[W] Shader shaders/planet.vert | shaders/planet.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing

[W] Shader shaders/planetgrid.vert | shaders/planetgrid.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing

[W] Shader shaders/atmosphere.vert | shaders/atmosphere.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing

[W] Shader shaders/unlit.vert | shaders/planet.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing

[W] Shader shaders/screenspace.vert | shaders/screenspace.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing

[W] Mod C:/Users/rmper/AppData/Roaming/Mindustry/mods/403481397canvas2.0.zip doesn't have a '[mod/plugin].[h]json' file, skipping.
[E] Failed to load mod file C:/Users/rmper/AppData/Roaming/Mindustry/mods/403481397canvas2.0.zip. Skipping.
[E] java.lang.IllegalArgumentException: Invalid file: No mod.json found.
	at mindustry.mod.Mods.loadMod(Mods.java:644)
	at mindustry.mod.Mods.loadMod(Mods.java:620)
	at mindustry.mod.Mods.load(Mods.java:275)
	at mindustry.Vars.init(Vars.java:288)
	at mindustry.Vars.loadAsync(Vars.java:225)
	at arc.assets.AssetManager$2.loadAsync(AssetManager.java:353)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:53)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:17)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[I] Loaded mod 'The Playground' in 15.8119ms
[I] Loaded mod 'Invincible Cheat Mod v6' in 6.3732ms
[I] Loaded mod 'example-mod' in 6.3936ms
[I] Loaded mod '[#25f12f]Vanilla Extended[]' in 4.1912ms
[I] Loaded mod 'Trade Terminals' in 1.1857ms
[I] Loaded mod 'classic-music' in 0.7855ms
[I] Loaded mod 'mindustry-classic' in 0.7999ms
[I] Loaded mod 'anuke-logic' in 1.2746ms
[I] Loaded mod 'cliff' in 0.5937ms
[I] Loaded mod 'dev-mode' in 0.6404ms
[I] Loaded mod 'entity-lib' in 0.8047ms
[I] Loaded mod 'modding-toolbox' in 0.7778ms
[I] Loaded mod 'pictologic' in 0.7148ms
[I] Loaded mod 'routorio' in 4.6593ms
[I] Loaded mod 'rtfm' in 1.1045ms
[I] Loaded mod 'signals' in 1.3066ms
[I] Loaded mod 'speed' in 0.6347ms
[I] Loaded mod 'ui-lib' in 0.6427ms
[I] Loaded mod 'unit-factory' in 0.6059ms
[I] Loaded mod 'vbucks' in 2.5569ms
[I] Loaded mod 'AdvanceContent' in 15.7414ms
[I] Loaded mod 'portal' in 1.4214ms
[I] Loaded mod 'substructure' in 1.8298ms
[I] Loaded mod 'upgraded-factories' in 1.3191ms
[I] Loaded mod 'inverted-machines' in 1.6536ms
[I] Loaded mod 'Vanilla Enhanced' in 2.2017ms
[I] Loaded mod 'exotic-mod' in 9.0587ms
[I] Loaded mod 'badguns' in 1.2511ms
[I] Loaded mod 'Decdustry' in 0.5918ms
[I] Loaded mod 'do-not-the-cat' in 0.597ms
[I] Loaded mod 'sandy-sand' in 5.8607ms
[I] Loaded mod 'purple-air' in 2.5217ms
[I] Loaded mod 'ohno-missiles' in 3.8955ms
[I] Loaded mod 'test-utils' in 3.6445ms
[I] Loaded mod 'vanilla-upgraded' in 19.8906ms
[I] Loaded mod 'hacker-tools' in 0.9251ms
[I] Loaded mod 'multi-lib2' in 0.6392ms
[I] Loaded mod 'hackustry' in 0.6824ms
[I] Loaded mod 'rpm' in 1.3747ms
[I] Loaded mod 'Testing' in 1.125ms
[I] Loaded mod 'pixelcraft' in 4.4068ms
[I] Loaded mod 'aperture-science' in 1.5732ms
[I] Loaded mod 'betamindy' in 58.3143ms
[E] Failed to load mod file C:/Users/rmper/AppData/Roaming/Mindustry/mods/sk7725BetaMindy.zip. Skipping.
[E] java.lang.IllegalArgumentException: A mod with the name 'betamindy' is already imported.
	at mindustry.mod.Mods.loadMod(Mods.java:671)
	at mindustry.mod.Mods.loadMod(Mods.java:620)
	at mindustry.mod.Mods.load(Mods.java:275)
	at mindustry.Vars.init(Vars.java:288)
	at mindustry.Vars.loadAsync(Vars.java:225)
	at arc.assets.AssetManager$2.loadAsync(AssetManager.java:353)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:53)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:17)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[E] Failed to load mod file C:/Users/rmper/AppData/Roaming/Mindustry/mods/sk7725BetaMindy1.zip. Skipping.
[E] java.lang.IllegalArgumentException: A mod with the name 'betamindy' is already imported.
	at mindustry.mod.Mods.loadMod(Mods.java:671)
	at mindustry.mod.Mods.loadMod(Mods.java:620)
	at mindustry.mod.Mods.load(Mods.java:275)
	at mindustry.Vars.init(Vars.java:288)
	at mindustry.Vars.loadAsync(Vars.java:225)
	at arc.assets.AssetManager$2.loadAsync(AssetManager.java:353)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:53)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:17)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[I] Loaded mod 'commandblocks' in 15.4127ms
[I] Loaded mod 'GamersMod' in 3.4618ms
[I] Loaded mod 'skillplus' in 0.7447ms
[I] Loaded mod 'testers' in 1.1547ms
[I] Loaded mod 'time-control' in 0.5583ms
[I] Loaded mod 'trains' in 0.9762ms
[I] Loaded mod 'reVision' in 1.2474ms
[I] Loaded mod '[#624200]Copper' in 1.1749ms
[I] Loaded mod '[orange]Mindustry [white]Space Expansion Pack' in 0.4976ms
[I] Loaded mod 'community-mod' in 0.7439ms
[I] Loaded mod 'bundle-chaos' in 0.5257ms
[E] Failed to load mod file C:/Users/rmper/AppData/Roaming/Mindustry/mods/valtsu41bundle-chaos.zip. Skipping.
[E] java.lang.IllegalArgumentException: A mod with the name 'bundle-chaos' is already imported.
	at mindustry.mod.Mods.loadMod(Mods.java:671)
	at mindustry.mod.Mods.loadMod(Mods.java:620)
	at mindustry.mod.Mods.load(Mods.java:275)
	at mindustry.Vars.init(Vars.java:288)
	at mindustry.Vars.loadAsync(Vars.java:225)
	at arc.assets.AssetManager$2.loadAsync(AssetManager.java:353)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:53)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:17)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[I] Loaded mod 'multi-lib' in 0.6044ms
[I] Loaded mod 'larger-cores' in 0.8071ms
[I] Loaded mod 'tfsyes' in 0.5991ms
[I] Loaded mod 'HackForAll' in 1.3216ms
[I] Loaded mod 'Canvas' in 2.706ms
[E] java.lang.NullPointerException
	at mindustry.io.SaveIO.getMeta(SaveIO.java:91)
	at mindustry.io.SaveIO.isSaveValid(SaveIO.java:69)
	at mindustry.io.SaveIO.isSaveValid(SaveIO.java:61)
	at mindustry.game.Saves.load(Saves.java:51)
	at mindustry.core.Control.loadAsync(Control.java:241)
	at arc.assets.AssetManager$2.loadAsync(AssetManager.java:353)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:53)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:17)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[E] arc.util.serialization.SerializationException: Serialization trace:
{}.sector
sector (mindustry.game.Rules)
	at arc.util.serialization.Json.readFields(Json.java:908)
	at arc.util.serialization.Json.readValue(Json.java:1083)
	at arc.util.serialization.Json.readValue(Json.java:984)
	at arc.util.serialization.Json.fromJson(Json.java:825)
	at mindustry.io.JsonIO.read(JsonIO.java:57)
	at mindustry.io.SaveVersion.getMeta(SaveVersion.java:42)
	at mindustry.io.SaveIO.getMeta(SaveIO.java:91)
	at mindustry.io.SaveIO.isSaveValid(SaveIO.java:69)
	at mindustry.io.SaveIO.isSaveValid(SaveIO.java:61)
	at mindustry.game.Saves.load(Saves.java:51)
	at mindustry.core.Control.loadAsync(Control.java:241)
	at arc.assets.AssetManager$2.loadAsync(AssetManager.java:353)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:53)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:17)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at mindustry.io.JsonIO$2.read(JsonIO.java:84)
	at mindustry.io.JsonIO$2.read(JsonIO.java:74)
	at arc.util.serialization.Json.readValue(Json.java:1090)
	at arc.util.serialization.Json.readFields(Json.java:901)
	... 17 more

[E] arc.util.serialization.SerializationException: Serialization trace:
{}.sector
sector (mindustry.game.Rules)
	at arc.util.serialization.Json.readFields(Json.java:908)
	at arc.util.serialization.Json.readValue(Json.java:1083)
	at arc.util.serialization.Json.readValue(Json.java:984)
	at arc.util.serialization.Json.fromJson(Json.java:825)
	at mindustry.io.JsonIO.read(JsonIO.java:57)
	at mindustry.io.SaveVersion.getMeta(SaveVersion.java:42)
	at mindustry.io.SaveIO.getMeta(SaveIO.java:91)
	at mindustry.io.SaveIO.isSaveValid(SaveIO.java:69)
	at mindustry.io.SaveIO.isSaveValid(SaveIO.java:61)
	at mindustry.game.Saves.load(Saves.java:51)
	at mindustry.core.Control.loadAsync(Control.java:241)
	at arc.assets.AssetManager$2.loadAsync(AssetManager.java:353)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:53)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:17)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at mindustry.io.JsonIO$2.read(JsonIO.java:84)
	at mindustry.io.JsonIO$2.read(JsonIO.java:74)
	at arc.util.serialization.Json.readValue(Json.java:1090)
	at arc.util.serialization.Json.readFields(Json.java:901)
	... 17 more

[E] arc.util.serialization.SerializationException: Serialization trace:
{}.sector
sector (mindustry.game.Rules)
	at arc.util.serialization.Json.readFields(Json.java:908)
	at arc.util.serialization.Json.readValue(Json.java:1083)
	at arc.util.serialization.Json.readValue(Json.java:984)
	at arc.util.serialization.Json.fromJson(Json.java:825)
	at mindustry.io.JsonIO.read(JsonIO.java:57)
	at mindustry.io.SaveVersion.getMeta(SaveVersion.java:42)
	at mindustry.io.SaveIO.getMeta(SaveIO.java:91)
	at mindustry.io.SaveIO.isSaveValid(SaveIO.java:69)
	at mindustry.io.SaveIO.isSaveValid(SaveIO.java:61)
	at mindustry.game.Saves.load(Saves.java:51)
	at mindustry.core.Control.loadAsync(Control.java:241)
	at arc.assets.AssetManager$2.loadAsync(AssetManager.java:353)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:53)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:17)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at mindustry.io.JsonIO$2.read(JsonIO.java:84)
	at mindustry.io.JsonIO$2.read(JsonIO.java:74)
	at arc.util.serialization.Json.readValue(Json.java:1090)
	at arc.util.serialization.Json.readFields(Json.java:901)
	... 17 more

[I] [BetaMindy]: InitCost start!
[I] [BetaMindy]: InitCost start!
[I] [BetaMindy]: InitCost start!
[I] Total time to load: 6418ms
[W] Shader bloomshaders/screenspace.vert | bloomshaders/bloom.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing

[W] Shader bloomshaders/screenspace.vert | bloomshaders/threshold.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing

[W] Shader bloomshaders/blurspace.vert | bloomshaders/gaussian.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing

[W] Shader shaders/cubemap.vert | shaders/cubemap.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing

[W] Shader bloomshaders/screenspace.vert | bloomshaders/alpha_bloom.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing

[W] Shader bloomshaders/screenspace.vert | bloomshaders/alpha_threshold.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing

[W] Shader bloomshaders/blurspace.vert | bloomshaders/alpha_gaussian.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing

[I] Fetching community servers at https://raw.githubusercontent.com/Anuken/Mindustry/master/servers_v6.json
[I] Fetched 24 community servers.

**Crash logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
No crash.
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- [x] **I have updated to the latest release (https://github.com/sk7725/BetaMindy/releases) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725.

**Comment by sk7725** [comment]
fixed, you got an outdated version
