### ISSUE TITLE
shader clashing

### ISSUE THREAD

**Issue by lokyinng** [sk7725/BetaMindy#78]
**Platform**: *Android//Windows/Linux*
windows 10 x64
**Build**: *The build number under the title in the main menu. Required.*
126.2
**Mod Version**: *(optional)*
latest actions mod version
**Issue**: *Explain your issue in detail.*
betamindy clashed by bittium wall/spike shader
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. Not required, but you will be asked for it in certain bugs.*

**Last log**: *The `last_log.txt` from your game folder (.../Mindustry). REQUIRED if a certain block is not working at ALL, usually the case in headless servers.*

**Crash logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

java.lang.IllegalArgumentException: Failed to compile shader: Vertex shader
WARNING: 0:7: '' :  #version directive missing

Fragment shader:
WARNING: 0:10: '' :  #version directive missing
WARNING: 0:95: 'assign' : implicit type conversion allowed from GLSL 1.20 
ERROR: 0:95: 'f' : syntax error syntax error

	at arc.graphics.gl.Shader.<init>(Shader.java:125)
	at arc.graphics.gl.Shader.<init>(Shader.java:130)
	at betamindy.graphics.MindyShaders$BlockShader.<init>(MindyShaders.java:34)
	at betamindy.graphics.MindyShaders$ResBlockShader.<init>(MindyShaders.java:52)
	at betamindy.graphics.MindyShaders.load(MindyShaders.java:18)
	at betamindy.BetaMindy.lambda$null$3(BetaMindy.java:71)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:150)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:44)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- [x] **I have updated to the latest release (https://github.com/sk7725/BetaMindy/releases) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725.

**Comment by sk7725** [comment]
fixed in latest action.

**Comment by lokyinng** [comment]
thanks
