### ISSUE TITLE
anucoin texture bugged and brokerage info clash

### ISSUE THREAD

**Issue by lokyinng** [sk7725/BetaMindy#97]
**Platform**: *Android//Windows/Linux*
same as last time
**Build**: *The build number under the title in the main menu. Required.*
still 126.2
**Mod Version**: *(optional)*
newest actions again
**Issue**: *Explain your issue in detail.*
1. anucoin texture bugged out
2. brokerage info clash
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
click the info of the brokerage
**Save file**: *The (zipped) save file you were playing on when the bug happened. Not required, but you will be asked for it in certain bugs.*

**Last log**: *The `last_log.txt` from your game folder (.../Mindustry). REQUIRED if a certain block is not working at ALL, usually the case in headless servers.*

**Crash logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
java.lang.RuntimeException: No stat entry found: "range" in block.
	at mindustry.world.meta.Stats.remove(Stats.java:100)
	at betamindy.world.blocks.defense.turrets.CoinTurret.setStats(CoinTurret.java:28)
	at mindustry.ctype.UnlockableContent.checkStats(UnlockableContent.java:59)
	at mindustry.ui.dialogs.ContentInfoDialog.show(ContentInfoDialog.java:26)
	at mindustry.ui.dialogs.ModsDialog.lambda$showMod$44(ModsDialog.java:369)
	at arc.scene.Element.lambda$clicked$2(Element.java:893)
	at arc.scene.Element$4.clicked(Element.java:902)
	at arc.scene.event.ClickListener.touchUp(ClickListener.java:77)
	at arc.scene.event.InputListener.handle(InputListener.java:31)
	at arc.scene.Scene.touchUp(Scene.java:360)
	at arc.input.InputMultiplexer.touchUp(InputMultiplexer.java:137)
	at arc.input.InputEventQueue.drain(InputEventQueue.java:71)
	at arc.backend.sdl.SdlInput.update(SdlInput.java:102)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:145)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:44)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- [x] **I have updated to the latest release (https://github.com/sk7725/BetaMindy/releases) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725.

**Comment by sk7725** [comment]
1. explain what exactly does "bugged out" look like
2. fixed
